VERSION 2.00
Begin Form Form1 
   AutoRedraw      =   -1  'True
   BorderStyle     =   3  'Fixed Double
   Caption         =   "Easy!"
   ClientHeight    =   4530
   ClientLeft      =   2340
   ClientTop       =   1455
   ClientWidth     =   5415
   ClipControls    =   0   'False
   ControlBox      =   0   'False
   DrawMode        =   9  'Mask Pen
   DrawWidth       =   5
   Height          =   4935
   Icon            =   EASY.FRX:0000
   Left            =   2280
   LinkTopic       =   "Form1"
   MaxButton       =   0   'False
   MinButton       =   0   'False
   ScaleHeight     =   4530
   ScaleWidth      =   5415
   Top             =   1110
   Width           =   5535
   Begin TextBox Text1 
      Height          =   285
      Left            =   2520
      TabIndex        =   17
      Text            =   "text"
      Top             =   4680
      Width           =   615
   End
   Begin FileListBox File1 
      Height          =   225
      Left            =   1200
      TabIndex        =   16
      Top             =   4680
      Visible         =   0   'False
      Width           =   1095
   End
   Begin DriveListBox Drive1 
      Height          =   315
      Left            =   120
      TabIndex        =   15
      Top             =   4680
      Visible         =   0   'False
      Width           =   855
   End
   Begin SSCommand Command3D0 
      BevelWidth      =   3
      Height          =   2415
      Index           =   0
      Left            =   1080
      Picture         =   EASY.FRX:0302
      RoundedCorners  =   0   'False
      TabIndex        =   0
      Top             =   1080
      Width           =   3255
   End
   Begin SSCommand Command3D1 
      AutoSize        =   2  'Adjust Button Size To Picture
      BevelWidth      =   5
      Height          =   1095
      Index           =   1
      Left            =   0
      Picture         =   EASY.FRX:81CC
      RoundedCorners  =   0   'False
      TabIndex        =   1
      Top             =   0
      Width           =   1095
   End
   Begin SSCommand Command3D6 
      BevelWidth      =   5
      Height          =   1215
      Index           =   6
      Left            =   0
      Picture         =   EASY.FRX:89A6
      RoundedCorners  =   0   'False
      TabIndex        =   6
      Top             =   1080
      Width           =   1095
   End
   Begin SSCommand Command3D8 
      BevelWidth      =   5
      Height          =   1215
      Index           =   8
      Left            =   0
      Picture         =   EASY.FRX:9180
      RoundedCorners  =   0   'False
      TabIndex        =   8
      Top             =   2280
      Width           =   1095
   End
   Begin SSCommand Command3D10 
      AutoSize        =   2  'Adjust Button Size To Picture
      BevelWidth      =   5
      Height          =   1095
      Index           =   10
      Left            =   0
      Picture         =   EASY.FRX:995A
      RoundedCorners  =   0   'False
      TabIndex        =   10
      Top             =   3480
      Width           =   1095
   End
   Begin SSCommand Command3D11 
      AutoSize        =   2  'Adjust Button Size To Picture
      BevelWidth      =   5
      Height          =   1095
      Index           =   11
      Left            =   1080
      Picture         =   EASY.FRX:A134
      RoundedCorners  =   0   'False
      TabIndex        =   11
      Top             =   3480
      Width           =   1095
   End
   Begin SSCommand Command3D12 
      AutoSize        =   2  'Adjust Button Size To Picture
      BevelWidth      =   5
      Height          =   1095
      Index           =   12
      Left            =   2160
      Picture         =   EASY.FRX:A90E
      RoundedCorners  =   0   'False
      TabIndex        =   12
      Top             =   3480
      Width           =   1095
   End
   Begin SSCommand Command3D13 
      AutoSize        =   2  'Adjust Button Size To Picture
      BevelWidth      =   5
      Height          =   1095
      Index           =   13
      Left            =   3240
      Picture         =   EASY.FRX:B0E8
      RoundedCorners  =   0   'False
      TabIndex        =   13
      Top             =   3480
      Width           =   1095
   End
   Begin SSCommand Command3D14 
      AutoSize        =   2  'Adjust Button Size To Picture
      BevelWidth      =   5
      Height          =   1095
      Index           =   14
      Left            =   4320
      Picture         =   EASY.FRX:B8C2
      RoundedCorners  =   0   'False
      TabIndex        =   14
      Top             =   3480
      Width           =   1095
   End
   Begin SSCommand Command3D9 
      BevelWidth      =   5
      Height          =   1215
      Index           =   9
      Left            =   4320
      Picture         =   EASY.FRX:C09C
      RoundedCorners  =   0   'False
      TabIndex        =   9
      Top             =   2280
      Width           =   1095
   End
   Begin SSCommand Command3D7 
      BevelWidth      =   5
      Height          =   1215
      Index           =   7
      Left            =   4320
      Picture         =   EASY.FRX:C876
      RoundedCorners  =   0   'False
      TabIndex        =   7
      Top             =   1080
      Width           =   1095
   End
   Begin SSCommand Command3D5 
      AutoSize        =   2  'Adjust Button Size To Picture
      BevelWidth      =   5
      Height          =   1095
      Index           =   5
      Left            =   4320
      Picture         =   EASY.FRX:D050
      RoundedCorners  =   0   'False
      TabIndex        =   5
      Top             =   0
      Width           =   1095
   End
   Begin SSCommand Command3D4 
      AutoSize        =   2  'Adjust Button Size To Picture
      BevelWidth      =   5
      Height          =   1095
      Index           =   4
      Left            =   3240
      Picture         =   EASY.FRX:D82A
      RoundedCorners  =   0   'False
      TabIndex        =   4
      Top             =   0
      Width           =   1095
   End
   Begin SSCommand Command3D3 
      AutoSize        =   2  'Adjust Button Size To Picture
      BevelWidth      =   5
      Height          =   1095
      Index           =   3
      Left            =   2160
      Picture         =   EASY.FRX:E004
      RoundedCorners  =   0   'False
      TabIndex        =   3
      Top             =   0
      Width           =   1095
   End
   Begin SSCommand Command3D2 
      AutoSize        =   2  'Adjust Button Size To Picture
      BevelWidth      =   5
      Height          =   1095
      Index           =   2
      Left            =   1080
      Picture         =   EASY.FRX:E7DE
      RoundedCorners  =   0   'False
      TabIndex        =   2
      Top             =   0
      Width           =   1095
   End
End

Sub Command3D14_Click (Index As Integer)
    End
End Sub

Sub Form_GotFocus ()
    form1.Refresh
End Sub

