#
# See "man 8 inetd" for more information.
#
# If you make changes to this file, either reboot your machine or send the
# inetd a HUP signal:
# Do a "ps x" as root and look up the pid of inetd. Then do a
# "kill -HUP <pid of inetd>".
# The inetd will re-read this file whenever it gets that signal.
#
# <service_name> <sock_type> <proto> <flags> <user> <server_path> <args>
#
# Echo, discard, daytime, and chargen are used primarily for testing.
##echo	stream	tcp	nowait	root	internal
##echo	dgram	udp	wait	root	internal
##discard	stream	tcp	nowait	root	internal
##discard	dgram	udp	wait	root	internal
##daytime	stream	tcp	nowait	root	internal
##daytime	dgram	udp	wait	root	internal
##chargen	stream	tcp	nowait	root	internal
##chargen	dgram	udp	wait	root	internal
##time  	stream 	tcp 	nowait 	root 	internal
##time  	dgram 	udp 	wait 	root 	internal

#
# These are standard services.
ftp	stream	tcp	nowait	root	/usr/sbin/tcpd	/usr/sbin/wu.ftpd -a
telnet	stream  tcp     nowait  root    /usr/sbin/tcpd	/usr/sbin/in.telnetd -h
#
# Use this one instead if you want to snoop on telnet users (try to use this
# for ethical purposes, ok folks?) :
#telnet	stream  tcp     nowait  root    /usr/sbin/tcpd	/usr/sbin/in.telnetsnoopd
#
# The line below is set up for running Smail:
#smtp	stream  tcp     nowait  root    /usr/sbin/tcpd	/usr/bin/rsmtp	-bs
#
# If you want to read NNTP news via TERM, comment out the nntp 
# line below, and use a command like this once the TERM
# connection is up:  tredir 119 my.nntp.host:119
# You'll also want to do this: set NNTPSERVER my.nntp.host ; export NNTPSERVER
#nntp	stream	tcp	nowait	root	/usr/sbin/tcpd	/usr/sbin/in.nntpd
#
# Shell, login, exec and talk are BSD protocols.
shell	stream	tcp	nowait	root	/usr/sbin/tcpd	/usr/sbin/in.rshd
login	stream	tcp	nowait	root	/usr/sbin/tcpd  /usr/sbin/in.rlogind
#exec	stream	tcp	nowait	root	/usr/sbin/tcpd	/usr/sbin/in.rexecd
talk	dgram	udp	wait	root	/usr/sbin/tcpd	/usr/sbin/in.ntalkd
ntalk	dgram	udp	wait	root	/usr/sbin/tcpd	/usr/sbin/in.ntalkd
#
# Pop mail servers
pop2	stream	tcp	nowait	root	/usr/sbin/tcpd	/usr/sbin/in.pop2d
pop3	stream	tcp	nowait	root	/usr/sbin/tcpd	/usr/sbin/in.pop3d
imap3	stream 	tcp 	nowait 	root	/usr/sbin/tcpd /usr/local/etc/in.imapd
imap2	stream 	tcp 	nowait 	root	/usr/sbin/tcpd /usr/local/etc/in.imapd

#
# The Internet UUCP service.
##uucp	stream	tcp	nowait	uucp	/usr/sbin/tcpd /usr/lib/uucp/uucico	-l
#
# Tftp service is provided primarily for booting.  Most sites
# run this only on machines acting as "boot servers." 
# Since these can be security holes, they are commented out by default.
#tftp	dgram	udp	wait	root	/usr/sbin/tcpd	/usr/sbin/in.tftpd
#bootps	dgram	udp	wait	root	/usr/sbin/tcpd	/usr/sbin/in.bootpd
#
# Finger, systat and netstat give out user information which may be
# valuable to potential "system crackers."  Many sites choose to disable 
# some or all of these services to improve security.
finger	stream	tcp	nowait	daemon	/usr/sbin/tcpd	/usr/sbin/in.fingerd
##systat	stream	tcp	nowait	guest	/usr/sbin/tcpd /usr/bin/ps -auwwx
## netstat	stream	tcp	nowait	guest	/usr/sbin/tcpd /bin/netstat	-f inet
#
# Ident service is used for net authentication
auth	stream	tcp	nowait	root	/usr/sbin/in.identd	in.identd
#
# These are to start Samba, an smb server that can export filesystems to
# Pathworks, Lanmanager for DOS, Windows for Workgroups, Windows95, Lanmanager
# for Windows, Lanmanager for OS/2, Windows NT, etc.  Lanmanager for dos is
# available via ftp from ftp.microsoft.com in bussys/MSclient/dos/. Please read
# the licensing stuff before downloading. Use the TCP/IP option in the client.
# Add your server to the \etc\lmhosts (or equivalent) file on the client.
#netbios-ssn 	stream 	tcp 	nowait 	root 	/usr/sbin/smbd 	smbd
#netbios-ns 	dgram 	udp 	wait 	root 	/usr/sbin/nmbd 	nmbd
#
# deslogin
des	stream	tcp	nowait	root	/usr/local/sbin/deslogind	deslogind -w global -n
#
# End of inetd.conf.
