# /etc/syslog.conf
# For info about the format of this file, see "man syslog.conf" (the BSD man
# page), and /usr/doc/sysklogd/README.linux.
#
# NOTE: YOU HAVE TO USE TABS HERE - NOT SPACES.
# I don't know why.
#

*.=info;*.=notice				/usr/adm/messages
*.=debug					/usr/adm/debug
*.warn						/usr/adm/syslog

#
# This might work instead to log on a remote host:
# *			@hostname
