<HTML><HEAD><TITLE>Template Message Board</TITLE></HEAD><BODY BACKGROUND="/Images/Backgrounds/bkgnd.jpg"><FONT SIZE=+1><B>Name:</B> Selena Sol<BR><B>Email:</B> <A HREF="mailto:selena@eff.org">selena@eff.org</A><BR><B>Date:</B> Nov 25,1995<BR><B>Subject:</B> Welcome to The Template BBS Version 2.0
<BR></FONT><B>Body:</B><BLOCKQUOTE>This version has implemented infinitely decending threads, a last modified
feature, an email update feature and, hopefully, the 
communication nof paragraph breaks

Feel free to post messages and test out the scritps and maybe even say hello.</BLOCKQUOTE><B>Replies:</B><BLOCKQUOTE><A HREF="http://www.nchgr.nih.gov/cgi-bin/BBS/Template/Scripts/generate_post.cgi?oldmid=61&mid=64">Subject-So do you pretty much have the idea?</A><BR></BLOCKQUOTE><CENTER><P><IMG SRC="/Images/Icons/Lines/smalline.gif"><P><A HREF="post_response.cgi?oldmid=61"><IMG SRC="/Images/Buttons/post_a_reply.gif" BORDER=0 ALT="[Posta Message]"></a>
<A HREF="gen_first_page.cgi?mid=1&oldmid=1"><IMG SRC="/Images/Buttons/message_archive_top.gif" BORDER=0 ALT="[Readthrough Message Archive]"></A>
<A HREF="get_last_update.cgi"><IMG SRC="/Images/Buttons/last_modified.gif"BORDER=0 ALT="[Last Modified List]"></A></CENTER></BODY></HTML>