# With this document, you define the name space that users see of your http
# server.

# See the tutorials at http://hoohoo.ncsa.uiuc.edu/docs/tutorials/ for
# more information.

# NCSA httpd (httpd@ncsa.uiuc.edu)


# 403 - FORBIDDEN 
# 404 - NOT_FOUND 
# 500 - SERVER_ERROR 
# 501 - NOT_IMPLEMENTED 

#ErrorDocument 302 /cgi-bin/redirect.cgi
#ErrorDocument 500 /errors/server.html
ErrorDocument 404 /errore.html
