anarch: /des-exch/images/anarch.map
bus: /des-exch/images/bus.map
hotel: /des-exch/images/hotel.map
hq-interni: /des-exch/images/hq-interni.map
hq: /des-exch/images/hq.map
index: /des-exch/images/index.map
luigi: /des-exch/images/luigi.map
mappa: /des-exch/images/mappa.map
news: /des-exch/images/news.map
office: /des-exch/images/office.map
street: /des-exch/images/street.map