"Discussion
"Open Software Foundation,
(192.80.63.253):
(Peered) "TRACK Distribution List"
(Peered) "TRACKers forum"
(Peered) (TeXMaG)
(Peered) A list for free-talking
(Peered) Advanced Dungeons and Dragons discu+
(Peered) Applications under BITNET
(Peered) BITNET Monitoring List
(Peered) BITNET Ne
(Peered) BITNET Standards List
(Peered) BITNET X400 List
(Peered) BITNIC
(Peered) Baltic Republics Discussion List
(Peered) CICS List
(Peered) CYBER List
(Peered) China News Digest (Global News)
(Peered) Computer Game
(Peered) Discussion about BITNET policies
(Peered) Discussion forum for
(Peered) Discussion of Ethics in Computing
(Peered) Discussion of Government Document I+
(Peered) Discussion of NETMON
(Peered) Domain discussion group
(Peered) Domains Discussion Group
(Peered) EARN Technical Group
(Peered) FORUM
(Peered) File transfer list
(Peered) History
(Peered) History Discussion
(Peered) IBM 370 Assembly Programming Discus+
(Peered) IBM Mainframe Discussion List
(Peered) IBM vs Waterloo SCRIPT discussion g+
(Peered) INFO-IBMPC Digest
(Peered) INFO-KERMIT Digest
(Peered) INFO-MAC Digest
(Peered) INFO-VAX Discussion
(Peered) Info-Amiga List
(Peered) Info-IBMPC
(Peered) Info-Nets List
(Peered) JES2 discussion group
(Peered) JNET Discussion Group
(Peered) LISTSERV give-and-take forum
(Peered) Link failure announcements
(Peered) Lista de Informaciones para la Red +
(Peered) Los Colombianos en el Exterior
(Peered) MUSIC/SP User discussion list
(Peered) Mail Discussion List
(Peered) Mainframe Operations Discussion List
(Peered) Minix operating system
(Peered) NEW-LIST - New List Announcements
(Peered) Network Sites Liaison
(Peered) Node Management Discussion
(Peered) PROFS discussion
(Peered) Personal UNIX on VM discussion
(Peered) Polymer Physics discussions
(Peered) R
(Peered) Risks List
(Peered) RusHist - Russian History Forum
(Peered) SAS(r) Discussion
(Peered) SECURITY Digest
(Peered) Software Licensing List
(Peered) SovHist - Soviet History Forum
(Peered) T
(Peered) TECH-L List
(Peered) TURBO C Discussion group.
(Peered) The Crosswell Mailer List
(Peered) The Future of BITNET
(Peered) The Hellenic
(Peered) The India Interest Group at
(Peered) The India News Network (at
(Peered) The Islamic Information & News Netw+
(Peered) The Pakistan News Service
(Peered) The SIMULA Language List
(Peered) The TeXnical topics list
(Peered) Traffic Monitoring List
(Peered) Traffic monitoring list
(Peered) Usage Guidelines List
(Peered) User Directory List
(Peered) User Services List
(Peered) Users Guide list
(Peered) VM System Editor List
(Peered) VM Utilities Discussion List
(Peered) VM low-key Tech-staff discussion
(Peered) VM/SP REXX Language Discussion List
(Peered) VM/XA Discussion Lis
(Repr+
(Represe+
(che
(come
(dir)
(language)
(per
(vedi
), 
). 
* * * * * * * * * * * * * * * * * * * * * *
, che
, full duplex
, i
, ma
------------
-----<
2.7.2g
2.7.2g+
2.7.2g.
2.7.2g.ID 
28800
6 p.m. - 6 a.m.
64 bytes from bix.com (192.80.63.253):
: s
: sm.
: sm. - Un
: vt.
: vt. -
>-----------------------------------------
ADministators'
AERA
AFRICA-
AISTF
AJCU
ALA
ALCUNI SITI
ARPAnet
ASCII
ATLAS
ATLAS C
ATLAS Collaboration sub-list:
ATLAS Collaboration sub-list: Inner
ATLAS Collaboration sub-list: Software (Repr+
ATLRD1
ATLRD2
ATLRD3
Academic
Access
Acronimo
Administr
Administration
Administrative
Administrator
Administrators
Advanced
Advisory
Affairs
Africa
Agriculture
Al menù principale, scegliete
Al momento non dispongo di informazioni.
Alliance For Computers and Writing
Alpha
America
American
Amiga
Analysis
Anche
Announcements
Anonymous
Apple
Application
Archie
Archie via e-mail
Archite
Arctic
Area
Asimov
Assoc
Association
Attualmente
Australia
BBS
BITNET
BITNIC
Berkeley
Bibliographic
Biology
Bisexual
Bitnet
Board
Brasileir
Brook
Bruce Sterling
Bulletin
Business
CAR
CHILE
COM
COMPUTER
CONS
CPRI: Subgroup - "codes" of Work Group 3 on +
CPRI: Work Group 3 on Codes and Structures.
CPT
CRIMINAL
CYBER
California
Campus
Campus-Size LAN Discussion Group
Canada
Canadian
Center
Centers
Central
Centre
Chapter
Chi usa Internet... e cosa ci fa?
Children
China
Chinese
Christian
Christianity
Class
Classe
Coalition
Collaboration
Collection
Collegamento ipertestuale con un
College
Come
Comitato
Comm
Committee
CommuniTree
Communication
Community
Comp
Composition
Compuserve
Computa
Computational
Computer
Computers
Computing
Conferenc
Conference
Conference Announcements lists
Conservati
Consortium
Consult
Control
Cooperative
Coordination
Coordinator
Corporation
Council
Crackdown
Culture
Curriculum
Cyberpunk
Cyberspace
Cyberspazio
DATABASE
DEFINITY
DISCUSSION
DOMAIN
Dall'inglese
Data
Database
Dead Runners Texas
Department
Design
Develop
Development
Di che software ho bisogno?
Digest
Digital
Directors
Directory
Discus
Discus+
Discussao
Discussi+
Discussio+
Discussion
Discussions
Diskussions
Disponibile 24 ore.
Distanc
Distribution
Division
Documentation
E VOI CI CHIAMATE CRIMINALI.
E' dotata di
E' un
EARN
Eastern
Economic
Editor
Educati
Education
Educational
Educator
Electronic
Electronic Frontier Foundation
Eletronic
Engineering
English
Environment
Esiste
Esistono
Ethics
Etim.:
Europe
European
Evaluation
Exchange
Exchange list for Department of Architecture+
Executive
Experimental Server, Montreal, Que
FISICA-L
FOR
FORUM
FTP
FUTURE-L
Facilities
Facility
Faculty
Fidonet
File
Financial
Florida
Force
Forum
Forum Eletronico de Debate e Troca de Inform+
Foundation
Franc
Fraternity
Frontier
Future
GARR-
GOPHER
GRAPH
General
Generalmente
Geograph
German
Gibson
Global
Gopher
Government
Graduate
Graphics
Group
Gruppo
Guide
Guidelines
HEALTH
HISTORY
HOSPEX
Habitat
Hacker
Health
Higher
History
Hospital Computer Network Discussion Group a+
Human
Humanities
Humber College Human Studies
Hungarian
I messaggi
I-KERMIT@
IBM
IBM-MAI
IBMPC
INDIA
INFO
INFO-
INFO-IBMPC
INFO-KERMIT
INFO-MAC
INFO-VAX
INFORMATI
INFORMAZIONI:
INTER
INTERNET
Il nome del file è
Illinois
Indiana
Indonesian
Industrial
Info
Info-Nets
Informacion
Informat+
Informatic
Information
Initiative
Inoltre
Institute
Institutional
Instruction
Inter
Interactive
Interest
Interfa
Internation
International
International Arctic Project
International Committee for Accessible Docum+
Internet
Internet navigation course for k-12 educator+
Internet...
Internet/BITNET Network Trainers
Internet: Ricerca e navigazione
Internet: Tipi di collegamento
Interpersonal Computing and Technology
Ipertesto
Israel
Issues
Italia
Italian
Italian Crackdown
Japa
Jewish
Journal
KIDCAFE
KIDLE
KIDLink
Kakuriron Kondankai Bulletin
Kentucky
Knowledge
LATIN
LIAISON
LIBRARY
LINKFAIL
LIS
LIST
LISTEARN Sample List. This is the list's hea+
LISTSERV
La directory
Language
Latin
Latin America Data Base
Latin American
Learning
Liaison
Librarians
Libraries
Library
Licensing
List
List.
Lista
Liste
Listesi
Listserv
Literature
Lo potete prelevare al seguente
Local
MAIL-L
MAPPA Trainers Networ
MIT
MS-DOS
Macintosh
Magazine
Mail
Mailing
Mainframe
Management
Manager
Material
Mathematic
McGill
Media
Medical
Medicine
Medieval
Miami
Michigan
Microcomputer
Microsoft
Milanese
Milano,
Mirrorshades
Missouri
Modula-2 (language) discussions
Monitoring
Morningstar
Morris
Mosaic
Multimedia
Music
NET
NETMON
NETWORK
NOT
Nathan Never
National
Nel
Nella
Nella directory
Net
Netscape
Network
Network Information Center di Internet
Networking
Networks
Neuromancer
New
News
Newsletter
No title defined
Node
Non
North
North Ridge Software Fix/PTF List
Officers
Offre tutti i collegamenti dal dial-up,
Oltre
Online
Open
Operations
Operazione Sundevil
Organization
Ovviamente
PFSICP-
PHYS
POLI
PROFS
PSYC
Pacific
Parallel
Per
Per maggior informazioni vedi anche
Personal
Personnel
Philosophy
Physics
Planning
Policy
Political
Posta elettronica
Potete scaricarlo dal seguente
Practic
President
Problem
Processing
Produc
Products
Professional
Progetto
Program
Programming
Project
Projects
Protocol
Psychology
Pubblicazioni elettroniche su
Public
Publications
Publish
Purdue Libraries
Quando
Questa
Questions
Questo
RESEARCH
REXX
RINAF
Realtà Virtuale e Cyberspazio
Redistribution
Region
Regional
Rehabilitation
Related
Relazioni sociali
Reporting
Research
Researchers In Population Aging Computer Con+
Resource
Resources
Rete
Rete Civica Milanese
Reti di BBS
Retrieval
Review
SBMICRO - Forum de Debates em micro eletroni+
SCRIPT
SECURITY
SGAN
SIMNET
SIMULA
SLIP
SUNY
SUNY Faculty Access to Computing Technology +
SUPER
Scholars
School
Science
Sciences
Scienti
Seminar
Server
Service
Services
Sistem
Social
Society
Society of Mexican American Engineers and Sc+
Software
Sono
Sony Computer Science Laboratory, Inc.
Special
Staff
Standards
State
Stati
Statistic
Steering
Sterling
Strategic Planning Committee, Professional D+
Student
Students
Studies
Studies in Communication and Information Tec+
Study
Supercomput
Support
Syndrome
System
Systems
TAMU China Club Discussion List
TCP/IP
TEACH
TECH-L
TESL
TEST
TRANS
TRANS-L
Tartisma
TeXnical
Teachers
Teaching
Tech
Technical
Technion
Technologi
Technology
Tecnologia dell'Informazione [Dal 1960]
Tel
Tel.0331/329900 fax 0331/329901. E-mail:
Telefonare a voce con Internet
Telematic
Telnet
Termin
Test
Testing
Texas
The
Theory
Tra gli altri servizi commerciali vedi anche
Trainers
Training
Trans
Transfer
Tunisian Information Office, Washington D.C.
Turkish
Tuttavia
U.T. System ITC
UNIVERSITY OF MISSOURI - Bill Meade -
UNIX
USENET
UUENCODE
Una
Undergraduate
United
Univ
Universit
University
University of
University of Melbourne, Australian Hub
Unix
Unixverstas Olutensin, Finlandia Vodka
User
User's
Users
Utilities
Uzerine
Vedi
Vedi anche
Veronica
Veterinary
Virginia
Virtual
WWW
Washington
Wayne Headrick
Western
William Gibson
Windows
Windows.
Women
Work
Working
Workshop
World
Writers
Writing
York
[tr.it.
a.m.
abbastanza
abbiamo
abbonamento
abbonarsi
about
accedere
access.usask.ca
accessi
accesso
addirittura
administr
aggiornat
aggiunge
agli
al posto dell'asterisco ho un numero compreso tra 0 e 255
al seguente indirizzo
alcune
alcuni
algoritmo
all'
all'indirizzo
all'interno
alla
alla connessione su linea dedicata.
alle
almeno
alternativ
altre
altri
altrimenti
altro
ambiente
american
anche
ancora
and
anima
anni
announcements
anonymous
appare
appartene
appartengono
appassionat
applicat
applicazion
apposit
appunto
archie
archite
argomenti
argomento
arriva
artificial
ascolta
aspetta
aspetti
associa
associazion
attiva
attività
attraverso
attual
attualmente
automaticamente
autori
avere
aveva
avevano
avrebbe
avrebbero
avven
azion
banche
base
bibliografi
biblioteche
binario
bisogna
bisogno
bisogno?
bix.com
bollett
bps
browser
calcol
calcolatore
calcolatori
cambia
campo
capacità
capire
carattere
caratteri
caratteristica
caratteristiche
casa
caso
cataloghi
categorie
centinaia
centri
centro
cercando
cercare
certo
che
che trasmettono alla velocità massima di
che trasmettono alla velocità massima di 28800
chi
chiama
chiamata
chiamato
chiave
chiavi
chieder
chiunque
ciascun
ciberspazio
cinema
cioè
circa
cittadini
città
ciò
client
codice
collaborazione
colleg
collega
collegamenti
collegamenti diretti (alla Rete) in linea commutata
collegamento
collegare
collegarsi
collegate
collegati
collegato
coloro
comandi
comando
combinazione
come
comincia
commercial
commerciale
communication
commutata
compar
compatta
complet
completamente
component
compra
compre
comprende
compres
compressione
computer
computer,
computer.
comune
comuni
comunicare
comunicazione
comunicazioni
comunità
comunque
con
conce
concetto
conferenze
conness
connessione
connetter
connettere
conoscenz
conoscer
consens
consente
consentir
consentito
consentiva
consentono
considerato
consiglio
consultazione
contatt
contattare
contemporaneamente
contenent
contengono
contenute
contenuti
contenuto
contiene
continua
contra
contribu
contro
controlla
controllo
convenient
convenzion
conversazioni
copia
copyright
corpo
correttamente
corrispond
cosa
costitui
costituzion
costo
costrui
così
creare
creato
creazione
crescita
crittograf
cui
cultura
cyberpunk
cyberspazio
d'Informacio
dagli
dai
dal
dall'
dall'altr
dall'indirizzo
dall'inglese
dall'utente
dalla
dalle
danneggia
danneggiano
database
dati
decisamente
dedicat
dedicata
defini
degli
dei
del
dell'
dell'Informazione
dell'Università
dell'a
dell'indirizzo
dell'informatica
dell'informazione
dell'interfaccia
dell'u
dell'utente
della
delle
dello
descrive
destina
destinatari
dettagliat
detto
di 
dial-up,
dibattit
differenti
differenza
difficil
diffonde
diffus
diffusione
digita
digitando
dimension
directory
direttamente
diretto
direzion
diritti
dischetti
disco
disco rigido
discu
discussao
discussi
discussion
discussions
disegna
disponibile
disponibili
disporre
disposizione
distanza
distribui
distribution
distribuzione
diventare
diversa
diverse
diversi
diverso
documenti
documento
domanda
dominio
dopo
dotata
dove
due
duplicazione
durante
e come molti documenti ufficiali è disponibile presso il
e-mail
economic
education
effettuare
effettuat
elaborat
elaborazion
electroni
elementi
elenco
elettronica
elettroniche
elettronici
elettronico
emulazione
era
erano
errore
errori
esattamente
esclusivamente
esegui
eseguibil
esempio
esempio,
esiste
esistono
esperienz
esperiment
espression
essere
faccine
facendo
facile
facili
failure
fanciers
fantascienza
fare
fatto
file
files
film
filosofi
fisicamente
fondamental
for
forma
formato
fornisce
forniscono
fornit
fornitor
forum
fosse
francais
freeware
from
ftpmail
funziona
funzione
funzioni
futuro
genera
general
generalmente
genere
gente
geografi
gestione
giochi
giornal
giorni
giorno
giovani
give-and-take
gli
global
gopher
govern
grado
grafica
grande
grandi
gratuitamente
grazie
group
gruppi
gruppo
hacker
hanno
hardware
http://www.
http://www.altair.it/cisv/
icmp_seq=
identifica
immagina
immagini
immediatamente
impegnat
impiega
implement
importante
importanti
indica
indicare
indirizzi
indirizzi Internet
indirizzo
indirizzo Internet
individu
infatti
infatti,
info
infor
informati
informatic
information
informazione
informazioni
ingegneri
inglese
inizi
inoltre,
insieme
inten
intende
inter
interattiv
interc
interes
interess
interessat
interfacce
interfaccia
internazional
interno
intorno
introdott
invece
invece,
inviare
inviati
ipertestual
issues
istituzion
istruzioni
italiana
italiane
italiani
italiano
l'Università
l'accesso
l'ambient
l'applicazione
l'elenco
l'indirizzo
l'informa
l'inter
l'interfaccia
l'introduzione
l'ultim
l'uso
l'utente
laboratorio
language
lavorare
lavoro
legge
legger
leggi
letteratura
lettere
letto
lettura
libera
liberamente
libri
libro
limitat
limitazion
linea
linee
linguaggio
list
list.
lista
liste
lists
livello
local
lontan
loro
luogo
macchina
macchine
magari
maggior
maggiori
mailing
mailing list
maniera
mano
massima
material
mediante
meglio
memoria
meno
mente
mentre
mercato
messaggi
messaggio
metodo
mette
mettere
mezzo
migliaia
miglior
migliore
milioni
militar
modalità
modem
modifica
modo
molte
molti
moltissim
molto
momento
mondiale
mondo
mondo.
monitor
motivo
movimenti
movimento
musical
nascita
natura
navigazione
nazional
necessari
necessariamente
necessario
necessit
negli
nei
nel
nell'ambiente
nella
nella directory
nelle
nello
nessun
network
news
newsgroup
newslette
nic.ddn.mil
nome
nome_del_file
non
normalmente
nostro
notevole
notiziari
notizie
numeri
numero
numerose
numerosi
nuova
nuove
nuovo
occorre
occupa
offre
offrire
oggetti
oggi
ogni
oltre
on-line
operativo
operazione
operazioni
oppure
organizza
organizzazion
origin
originale
ottenere
ovviamente
p.m.
pacchetti
pacchetto
pagine
para
parametr
parla
parlare
parola
parole
parte
partecipanti
parti
particolare
particolari
particolarmente
partire
paziente
pensa
per
per quanto riguarda
perché
pericolo
periodo
permanent
permesso
permette
permettono
persino
persona
personaggio
personal
persone
piattaform
piccolo
piuttosto
più
pochi
poi
point
policies
politic
politica
porta
portat
possa
possibile
possibili
possibilità
possono
posta
posta elettronica
posti
posto
potenti
potenza
potenzialità
poter
potere
potete
poteva
potrebbe
pratica
praticamente
precedent
preci
preferisc
prelevare
presenta
presente
presenti
presenz
presso
prima
prime
primi
primo
principale
principali
privata
privati
probabilment
problema
problemi
processo
prodott
produttor
progettato
progettazione
progetti
progetto
program
programma
programma,
programmatori
programmi
progress
propri
propria
proprie
proprio
prossim
protocolli
protocollo
protocollo di trasmissione
prova
provenienti
provider
pub
pubblica
pubblicazion
pubbliche
pubblici
pubblico
punto
può
qualche
qualcosa
qualcuno
quale
quali
qualsiasi
qualunque
quando
quantità
quanto
quella
quelle
quelli
quello
quest'ultim
questa
queste
questi
question
questo
quindi
raccolt
raccont
raddoppiament
radical
radio
radioamator
raggiung
raggiungere
ragion
rappresenta
realizza
realizzare
realizzazione
realtà
realtà virtual
recentemente
recupera
redistribution
region
regist
registrazione
regole
related
relativamente
relative
relativi
relazion
release
remoto
research
responsabil
rete
rete.
reti
reti di BBS
riabilitazione
ricerca
ricercatori
ricerche
ricevere
richiede
richiest
richiesta
riconoscer
riconosci
ricord
ricordar
riferiment
riguarda
riguardanti
rilascia
riman
risoluzione
risolvere
risorse
rispetto
risponder
risposta
risulta
riuscit
rivista
riviste
rtfm.mit.ed
ruolo
sapere
sarebbe
sarebbero
sarà
scambiar
scambio
scarica
sceglie
scelt
scenari
schermo
scientific
scienz
scopo
scritta
scritti
scritto
scrivere
seconda
secondo
segnal
seguente
seguito
sembra
semplice
semplicemente
sempre
senso
senza
sequenza
serie
serve
server
service
servizi
servizio
session
settore
shareware
sia
siano
sicuramente
sicurezza
significa
significato
simile
simili
simulator
simulazione
singol
sistema
sistemi
siti
sito
situat
sm.
sobre
sociale
sociali
società
software
solamente
solito
solo
soluzion
sono
soprattutto
sorgent
sorprende
sotto
sottodirectory
sottodominio
spara-spara
spazio
speci
special
specific
specifica
spedire
speriment
spesso
spettacol
spostarsi
sta
stampa
standard
stanno
stata
state
stati
stato
stessa
stessi
stesso
stimol
storia
strumenti
strumento
struttura
student
sua
sub-list:
successiv
suddivis
sufficient
sui
sul
sulla
sulle
sumex-aim.stanford.edu
suo
suoi
supercomputer
superiori
suppor
supporto
sviluppa
sviluppat
sviluppato
sviluppo
sysop
system
systems
talvolta
tanto
tastiera
tecniche
tecnologia
tecnologic
tecnologie
telecomunicazion
telefon
telefonic
telefonica
telefoniche
telefono
telemati
telematica
telematiche
televisione
televisiv
telnet
tempo
tentativ
termina
terminale
termine
test
testo
the
tipo
topics
tra
tradizion
tramite
trasferi
trasferiment
trasferir
trasforma
trasmettere
trasmettono
trasmissione
tratt
tratta
tridimensional
troppo
trova
trovano
trovare
trovat
tutta
tuttavia
tutte
tutti
tutto
ufficiali
ultim
un'altra
un'interfaccia
un'organizzazione
una
underground
università
uno
usa
usando
usare
usata
usato
user-id
users
utente
utenti
utilizza
utilizzando
utilizzare
utilizzat
vantaggio
variabile
variabili
variant
varie
vecchi
vedere
vedi
veloce
velocità
vengono
veramente
verific
verranno
verrà
versione
versioni
verso
via
vicino
video
viene
virtuale
virtuale.
virtuali
virtualmente
virus
vista
visto
visualizza
volete
volta
vostra
vostro
vostro_nome
vt.
vuole
workstation
wuarchive.wustl.edu
